// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Footer documents */
interface FooterDocumentData {
    /**
     * Copyright Text field in *Footer*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.copyright_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    copyright_text: prismicT.RichTextField;
    /**
     * Slice Zone field in *Footer*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: footer.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<FooterDocumentDataSlicesSlice>;
}
/**
 * Slice for *Footer → Slice Zone*
 *
 */
type FooterDocumentDataSlicesSlice = LinksBlockSlice;
/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<FooterDocumentData>, "footer", Lang>;
/** Content for Header documents */
interface HeaderDocumentData {
    /**
     * Logo field in *Header*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: header.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * CTA Text field in *Header*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: header.cta_text
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta_text: prismicT.KeyTextField;
    /**
     * CTA Link field in *Header*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: header.cta_link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    cta_link: prismicT.LinkField;
    /**
     * Slice Zone field in *Header*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: header.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HeaderDocumentDataSlicesSlice>;
}
/**
 * Slice for *Header → Slice Zone*
 *
 */
type HeaderDocumentDataSlicesSlice = NavigationLinkSlice;
/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<HeaderDocumentData>, "header", Lang>;
/** Content for Home Page documents */
interface HomePageDocumentData {
    /**
     * Title field in *Home Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Home Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomePageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Home Page → Slice Zone*
 *
 */
type HomePageDocumentDataSlicesSlice = SectionBlockSlice | CardsBlockSlice | BannerBlockSlice | GridBlockSlice | LinksBlockSlice;
/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<HomePageDocumentData>, "home_page", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = SectionBlockSlice | BannerBlockSlice | CardsBlockSlice | GridBlockSlice | LinksBlockSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Service documents */
interface ServiceDocumentData {
    /**
     * Title field in *Service*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: service.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Slice Zone field in *Service*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: service.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ServiceDocumentDataSlicesSlice>;
}
/**
 * Slice for *Service → Slice Zone*
 *
 */
type ServiceDocumentDataSlicesSlice = SectionBlockSlice | BannerBlockSlice | CardsBlockSlice | GridBlockSlice | LinksBlockSlice;
/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ServiceDocumentData>, "service", Lang>;
export type AllDocumentTypes = FooterDocument | HeaderDocument | HomePageDocument | PageDocument | ServiceDocument;
/**
 * Primary content in BannerBlock → Primary
 *
 */
interface BannerBlockSliceDefaultPrimary {
    /**
     * Title field in *BannerBlock → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: banner_block.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *BannerBlock → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: banner_block.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Background Image field in *BannerBlock → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: banner_block.primary.background_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_image: prismicT.ImageField<never>;
    /**
     * Image field in *BannerBlock → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: banner_block.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Text Colour field in *BannerBlock → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: banner_block.primary.text_colour
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    text_colour: prismicT.BooleanField;
}
/**
 * Item in BannerBlock → Items
 *
 */
export interface BannerBlockSliceDefaultItem {
    /**
     * CTA Text field in *BannerBlock → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner_block.items[].cta_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta_text: prismicT.KeyTextField;
    /**
     * CTA Link field in *BannerBlock → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: banner_block.items[].cta_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    cta_link: prismicT.LinkField;
    /**
     * Style field in *BannerBlock → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: banner_block.items[].style
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    style: prismicT.SelectField<"Button Primary" | "Button Secondary" | "Button Tertiary">;
}
/**
 * Default variation for BannerBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `BannerBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerBlockSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<BannerBlockSliceDefaultPrimary>, Simplify<BannerBlockSliceDefaultItem>>;
/**
 * Slice variation for *BannerBlock*
 *
 */
type BannerBlockSliceVariation = BannerBlockSliceDefault;
/**
 * BannerBlock Shared Slice
 *
 * - **API ID**: `banner_block`
 * - **Description**: `BannerBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerBlockSlice = prismicT.SharedSlice<"banner_block", BannerBlockSliceVariation>;
/**
 * Primary content in CardsBlock → Primary
 *
 */
interface CardsBlockSliceDefaultPrimary {
    /**
     * Title field in *CardsBlock → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: cards_block.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *CardsBlock → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: cards_block.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Background Image field in *CardsBlock → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: cards_block.primary.background_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_image: prismicT.ImageField<never>;
    /**
     * Background Colour field in *CardsBlock → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: cards_block.primary.background_colour
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    background_colour: prismicT.BooleanField;
    /**
     * Columns field in *CardsBlock → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: cards_block.primary.columns
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    columns: prismicT.SelectField<"2" | "3" | "4" | "5" | "6">;
}
/**
 * Item in CardsBlock → Items
 *
 */
export interface CardsBlockSliceDefaultItem {
    /**
     * Item Heading field in *CardsBlock → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cards_block.items[].item_heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    item_heading: prismicT.KeyTextField;
    /**
     * Item Description field in *CardsBlock → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cards_block.items[].item_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    item_description: prismicT.RichTextField;
    /**
     * Item Image field in *CardsBlock → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: cards_block.items[].item_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    item_image: prismicT.ImageField<never>;
    /**
     * Item CTA Text field in *CardsBlock → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: cards_block.items[].item_cta_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    item_cta_text: prismicT.KeyTextField;
    /**
     * Item CTA Link field in *CardsBlock → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: cards_block.items[].item_cta_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    item_cta_link: prismicT.LinkField;
}
/**
 * Default variation for CardsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `CardsBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CardsBlockSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<CardsBlockSliceDefaultPrimary>, Simplify<CardsBlockSliceDefaultItem>>;
/**
 * Slice variation for *CardsBlock*
 *
 */
type CardsBlockSliceVariation = CardsBlockSliceDefault;
/**
 * CardsBlock Shared Slice
 *
 * - **API ID**: `cards_block`
 * - **Description**: `CardsBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CardsBlockSlice = prismicT.SharedSlice<"cards_block", CardsBlockSliceVariation>;
/**
 * Primary content in GridBlock → Primary
 *
 */
interface GridBlockSliceDefaultPrimary {
    /**
     * Title field in *GridBlock → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: grid_block.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *GridBlock → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: grid_block.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Columns field in *GridBlock → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: grid_block.primary.columns
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    columns: prismicT.SelectField<"2" | "3" | "4" | "5" | "6">;
    /**
     * Background Image field in *GridBlock → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: grid_block.primary.background_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_image: prismicT.ImageField<never>;
    /**
     * Background Colour field in *GridBlock → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: grid_block.primary.background_colour
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    background_colour: prismicT.BooleanField;
    /**
     * Text Colour field in *GridBlock → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: grid_block.primary.text_colour
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    text_colour: prismicT.BooleanField;
}
/**
 * Item in GridBlock → Items
 *
 */
export interface GridBlockSliceDefaultItem {
    /**
     * Item Heading field in *GridBlock → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: grid_block.items[].item_heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    item_heading: prismicT.KeyTextField;
    /**
     * Item Description field in *GridBlock → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: grid_block.items[].item_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    item_description: prismicT.RichTextField;
    /**
     * Item Image field in *GridBlock → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: grid_block.items[].item_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    item_image: prismicT.ImageField<never>;
    /**
     * Item CTA Link field in *GridBlock → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: grid_block.items[].item_cta_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    item_cta_link: prismicT.LinkField;
    /**
     * Item CTA Text field in *GridBlock → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: grid_block.items[].item_cta_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    item_cta_text: prismicT.KeyTextField;
}
/**
 * Default variation for GridBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `GridBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GridBlockSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<GridBlockSliceDefaultPrimary>, Simplify<GridBlockSliceDefaultItem>>;
/**
 * Slice variation for *GridBlock*
 *
 */
type GridBlockSliceVariation = GridBlockSliceDefault;
/**
 * GridBlock Shared Slice
 *
 * - **API ID**: `grid_block`
 * - **Description**: `GridBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type GridBlockSlice = prismicT.SharedSlice<"grid_block", GridBlockSliceVariation>;
/**
 * Primary content in LinksBlock → Primary
 *
 */
interface LinksBlockSliceDefaultPrimary {
    /**
     * Heading field in *LinksBlock → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: links_block.primary.heading
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    heading: prismicT.TitleField;
    /**
     * Description field in *LinksBlock → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: links_block.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in LinksBlock → Items
 *
 */
export interface LinksBlockSliceDefaultItem {
    /**
     * Link field in *LinksBlock → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: links_block.items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * Link Text field in *LinksBlock → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: links_block.items[].link_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    link_text: prismicT.KeyTextField;
}
/**
 * Default variation for LinksBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `LinksBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LinksBlockSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<LinksBlockSliceDefaultPrimary>, Simplify<LinksBlockSliceDefaultItem>>;
/**
 * Slice variation for *LinksBlock*
 *
 */
type LinksBlockSliceVariation = LinksBlockSliceDefault;
/**
 * LinksBlock Shared Slice
 *
 * - **API ID**: `links_block`
 * - **Description**: `LinksBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LinksBlockSlice = prismicT.SharedSlice<"links_block", LinksBlockSliceVariation>;
/**
 * Primary content in NavigationLink → Primary
 *
 */
interface NavigationLinkSliceDefaultPrimary {
    /**
     * Text field in *NavigationLink → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_link.primary.text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    text: prismicT.KeyTextField;
    /**
     * Link field in *NavigationLink → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_link.primary.link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Item in NavigationLink → Items
 *
 */
export interface NavigationLinkSliceDefaultItem {
    /**
     * Child Text field in *NavigationLink → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_link.items[].child_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    child_text: prismicT.KeyTextField;
    /**
     * Child Link field in *NavigationLink → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation_link.items[].child_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    child_link: prismicT.LinkField;
}
/**
 * Default variation for NavigationLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: `NavigationLink`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavigationLinkSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<NavigationLinkSliceDefaultPrimary>, Simplify<NavigationLinkSliceDefaultItem>>;
/**
 * Slice variation for *NavigationLink*
 *
 */
type NavigationLinkSliceVariation = NavigationLinkSliceDefault;
/**
 * NavigationLink Shared Slice
 *
 * - **API ID**: `navigation_link`
 * - **Description**: `NavigationLink`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavigationLinkSlice = prismicT.SharedSlice<"navigation_link", NavigationLinkSliceVariation>;
/**
 * Primary content in SectionBlock → Primary
 *
 */
interface SectionBlockSliceDefaultPrimary {
    /**
     * Title field in *SectionBlock → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: section_block.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *SectionBlock → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: section_block.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Background Image field in *SectionBlock → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: section_block.primary.background_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    background_image: prismicT.ImageField<never>;
    /**
     * Image field in *SectionBlock → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: section_block.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Style field in *SectionBlock → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: section_block.primary.style
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    style: prismicT.SelectField<"Image Right" | "Image Left" | "Centered">;
    /**
     * Background Colour field in *SectionBlock → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: section_block.primary.background_colour
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    background_colour: prismicT.BooleanField;
    /**
     * Text Colour field in *SectionBlock → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: section_block.primary.text_colour
     * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
     *
     */
    text_colour: prismicT.BooleanField;
}
/**
 * Item in SectionBlock → Items
 *
 */
export interface SectionBlockSliceDefaultItem {
    /**
     * CTA Text field in *SectionBlock → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: section_block.items[].cta_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta_text: prismicT.KeyTextField;
    /**
     * CTA Link field in *SectionBlock → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: section_block.items[].cta_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    cta_link: prismicT.LinkField;
    /**
     * CTA Style field in *SectionBlock → Items*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: section_block.items[].cta_style
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    cta_style: prismicT.SelectField<"Button Primary" | "Button Secondary" | "Button Tertiary">;
}
/**
 * Default variation for SectionBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `SectionBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SectionBlockSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<SectionBlockSliceDefaultPrimary>, Simplify<SectionBlockSliceDefaultItem>>;
/**
 * Slice variation for *SectionBlock*
 *
 */
type SectionBlockSliceVariation = SectionBlockSliceDefault;
/**
 * SectionBlock Shared Slice
 *
 * - **API ID**: `section_block`
 * - **Description**: `SectionBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SectionBlockSlice = prismicT.SharedSlice<"section_block", SectionBlockSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { FooterDocumentData, FooterDocumentDataSlicesSlice, FooterDocument, HeaderDocumentData, HeaderDocumentDataSlicesSlice, HeaderDocument, HomePageDocumentData, HomePageDocumentDataSlicesSlice, HomePageDocument, PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, ServiceDocumentData, ServiceDocumentDataSlicesSlice, ServiceDocument, AllDocumentTypes, BannerBlockSliceDefaultPrimary, BannerBlockSliceDefaultItem, BannerBlockSliceDefault, BannerBlockSliceVariation, BannerBlockSlice, CardsBlockSliceDefaultPrimary, CardsBlockSliceDefaultItem, CardsBlockSliceDefault, CardsBlockSliceVariation, CardsBlockSlice, GridBlockSliceDefaultPrimary, GridBlockSliceDefaultItem, GridBlockSliceDefault, GridBlockSliceVariation, GridBlockSlice, LinksBlockSliceDefaultPrimary, LinksBlockSliceDefaultItem, LinksBlockSliceDefault, LinksBlockSliceVariation, LinksBlockSlice, NavigationLinkSliceDefaultPrimary, NavigationLinkSliceDefaultItem, NavigationLinkSliceDefault, NavigationLinkSliceVariation, NavigationLinkSlice, SectionBlockSliceDefaultPrimary, SectionBlockSliceDefaultItem, SectionBlockSliceDefault, SectionBlockSliceVariation, SectionBlockSlice };
    }
}
