// Code generated by Slice Machine. DO NOT EDIT.

import BannerBlock from './BannerBlock';
import CardsBlock from './CardsBlock';
import GridBlock from './GridBlock';
import LinksBlock from './LinksBlock';
import NavigationLink from './NavigationLink';
import SectionBlock from './SectionBlock';

export {
	BannerBlock,
	CardsBlock,
	GridBlock,
	LinksBlock,
	NavigationLink,
	SectionBlock,
};

export const components = {
	banner_block: BannerBlock,
	cards_block: CardsBlock,
	grid_block: GridBlock,
	links_block: LinksBlock,
	navigation_link: NavigationLink,
	section_block: SectionBlock,
};
